/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.phyisics.views.expansion;

/**
 *
 * @author derickfelix
 */
public class LinearForm extends javax.swing.JFrame {

    /**
     * Creates new form DilatationForm
     */
    public LinearForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneResult = new javax.swing.JPanel();
        btnCalcule = new javax.swing.JButton();
        lblTitleSelected = new javax.swing.JLabel();
        lblResult = new javax.swing.JLabel();
        paneValues = new javax.swing.JPanel();
        lblLinearExpansionIcon = new javax.swing.JLabel();
        lblTitleInitialL = new javax.swing.JLabel();
        lblTitleFinalL = new javax.swing.JLabel();
        lblTitleInitialT = new javax.swing.JLabel();
        lblTitleAlpha = new javax.swing.JLabel();
        txtInitialL = new javax.swing.JTextField();
        txtInitialT = new javax.swing.JTextField();
        txtAlpha = new javax.swing.JTextField();
        lblTitleFinalT = new javax.swing.JLabel();
        txtFinalT = new javax.swing.JTextField();
        txtFinalL = new javax.swing.JTextField();
        paneSelect = new javax.swing.JPanel();
        btnAlpha = new javax.swing.JButton();
        btnTemperature = new javax.swing.JButton();
        btnLength = new javax.swing.JButton();
        btnLength1 = new javax.swing.JButton();
        btnLength2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Thermodynamics - Linear Expansion");

        paneResult.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Result", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14))); // NOI18N

        btnCalcule.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        btnCalcule.setText("Calcule");

        lblTitleSelected.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        lblTitleSelected.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleSelected.setText("Selected");

        lblResult.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        lblResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResult.setText("00");

        javax.swing.GroupLayout paneResultLayout = new javax.swing.GroupLayout(paneResult);
        paneResult.setLayout(paneResultLayout);
        paneResultLayout.setHorizontalGroup(
            paneResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneResultLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCalcule, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTitleSelected, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        paneResultLayout.setVerticalGroup(
            paneResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneResultLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(btnCalcule)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitleSelected)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblResult)
                .addContainerGap())
        );

        paneValues.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Linear Expansion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 18))); // NOI18N

        lblLinearExpansionIcon.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        lblLinearExpansionIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLinearExpansionIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/phyisics/resources/linear_expansion.jpg"))); // NOI18N

        lblTitleInitialL.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        lblTitleInitialL.setText("<html>L<sub>I</sub></html>");

        lblTitleFinalL.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        lblTitleFinalL.setText("<html>L<sub>F</sub></html>");

        lblTitleInitialT.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        lblTitleInitialT.setText("<html>&theta;<sub>I</sub></html>");

        lblTitleAlpha.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        lblTitleAlpha.setText("<html>&alpha;</html>");

        txtInitialL.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        txtInitialL.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtInitialT.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        txtInitialT.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtAlpha.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        txtAlpha.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblTitleFinalT.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        lblTitleFinalT.setText("<html>&theta;<sub>F</sub></html>");

        txtFinalT.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        txtFinalT.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtFinalL.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        txtFinalL.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout paneValuesLayout = new javax.swing.GroupLayout(paneValues);
        paneValues.setLayout(paneValuesLayout);
        paneValuesLayout.setHorizontalGroup(
            paneValuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneValuesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneValuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtInitialL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitleInitialL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitleFinalL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFinalL, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblLinearExpansionIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneValuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneValuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtFinalT, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addComponent(lblTitleFinalT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblTitleInitialT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtInitialT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneValuesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitleAlpha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtAlpha, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175))
        );
        paneValuesLayout.setVerticalGroup(
            paneValuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneValuesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(paneValuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblLinearExpansionIcon)
                    .addGroup(paneValuesLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(lblTitleInitialL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtInitialL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(lblTitleFinalL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFinalL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneValuesLayout.createSequentialGroup()
                        .addComponent(lblTitleInitialT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtInitialT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTitleFinalT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFinalT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(paneValuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAlpha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitleAlpha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58))
        );

        paneSelect.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Select One", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14))); // NOI18N

        btnAlpha.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        btnAlpha.setText("Alpha");

        btnTemperature.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        btnTemperature.setText("<html>&theta;<sub>I</sub></html>");

        btnLength.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        btnLength.setText("<html>&theta;<sub>F</sub></html>");

        btnLength1.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        btnLength1.setText("<html>L<sub>I</sub></html>");

        btnLength2.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        btnLength2.setText("<html>L<sub>F</sub></html>");

        javax.swing.GroupLayout paneSelectLayout = new javax.swing.GroupLayout(paneSelect);
        paneSelect.setLayout(paneSelectLayout);
        paneSelectLayout.setHorizontalGroup(
            paneSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneSelectLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTemperature)
                    .addComponent(btnAlpha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLength)
                    .addComponent(btnLength1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(btnLength2, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                .addContainerGap())
        );
        paneSelectLayout.setVerticalGroup(
            paneSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneSelectLayout.createSequentialGroup()
                .addComponent(btnAlpha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLength1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLength2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(paneValues, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paneResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paneSelect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paneValues, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(paneSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(paneResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LinearForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LinearForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LinearForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LinearForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LinearForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlpha;
    private javax.swing.JButton btnCalcule;
    private javax.swing.JButton btnLength;
    private javax.swing.JButton btnLength1;
    private javax.swing.JButton btnLength2;
    private javax.swing.JButton btnTemperature;
    private javax.swing.JLabel lblLinearExpansionIcon;
    private javax.swing.JLabel lblResult;
    private javax.swing.JLabel lblTitleAlpha;
    private javax.swing.JLabel lblTitleFinalL;
    private javax.swing.JLabel lblTitleFinalT;
    private javax.swing.JLabel lblTitleInitialL;
    private javax.swing.JLabel lblTitleInitialT;
    private javax.swing.JLabel lblTitleSelected;
    private javax.swing.JPanel paneResult;
    private javax.swing.JPanel paneSelect;
    private javax.swing.JPanel paneValues;
    private javax.swing.JTextField txtAlpha;
    private javax.swing.JTextField txtFinalL;
    private javax.swing.JTextField txtFinalT;
    private javax.swing.JTextField txtInitialL;
    private javax.swing.JTextField txtInitialT;
    // End of variables declaration//GEN-END:variables
}
