/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.phyisics.views;

import com.phyisics.controllers.expansion.LinearController;
import java.awt.Color;

/**
 *
 * @author derickfelix
 */
public class LinearExpansion extends javax.swing.JFrame {

    private LinearController lc;
    private char selected;

    /**
     * Creates new form DilatationForm
     */
    public LinearExpansion() {
        initComponents();
        lc = new LinearController();
        selectEnabledComponents(false, false, false, false, false);
    }

    /**
     * Change the Enabled for each elements
     *
     * @param il - txtInitialL
     * @param it - txtInitialT
     * @param fl - txtFinalL
     * @param ft - txtFinalT
     * @param al - txtAlpha
     */
    private void selectEnabledComponents(boolean il, boolean it, boolean fl, boolean ft, boolean al) {
        // Handle the placeholder by the desired field
        lc.placeHolder(it, txtInitialT, "43.2");
        lc.placeHolder(fl, txtFinalL, "2.24");
        lc.placeHolder(ft, txtFinalT, "243.2");
        lc.placeHolder(al, txtAlpha, "6.4e-6");
        // TextFields
        this.txtInitialL.setEnabled(il);
        this.txtInitialT.setEnabled(it);
        this.txtFinalL.setEnabled(fl);
        this.txtFinalT.setEnabled(ft);
        this.txtAlpha.setEnabled(al);
        // Labels
        this.lblTitleInitialL.setEnabled(il);
        this.lblTitleInitialT.setEnabled(it);
        this.lblTitleFinalL.setEnabled(fl);
        this.lblTitleFinalT.setEnabled(ft);
        this.lblTitleAlpha.setEnabled(al);
        // Update Result Label
        lblResult.setForeground(Color.darkGray);
        lblResult.setText("00");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneResult = new javax.swing.JPanel();
        btnCalculate = new javax.swing.JButton();
        lblTitleSelected = new javax.swing.JLabel();
        lblResult = new javax.swing.JLabel();
        paneValues = new javax.swing.JPanel();
        lblLinearExpansionIcon = new javax.swing.JLabel();
        lblTitleInitialL = new javax.swing.JLabel();
        lblTitleFinalL = new javax.swing.JLabel();
        lblTitleInitialT = new javax.swing.JLabel();
        lblTitleAlpha = new javax.swing.JLabel();
        txtInitialL = new javax.swing.JTextField();
        txtInitialT = new javax.swing.JTextField();
        txtAlpha = new javax.swing.JTextField();
        lblTitleFinalT = new javax.swing.JLabel();
        txtFinalT = new javax.swing.JTextField();
        txtFinalL = new javax.swing.JTextField();
        paneSelect = new javax.swing.JPanel();
        btnAlpha = new javax.swing.JButton();
        btnInitialT = new javax.swing.JButton();
        btnFinalT = new javax.swing.JButton();
        btnFinalL = new javax.swing.JButton();
        paneMoreInformation = new javax.swing.JPanel();
        lblTitleDeltaL = new javax.swing.JLabel();
        lblTitleDeltaT = new javax.swing.JLabel();
        lblDeltaL = new javax.swing.JLabel();
        lblDeltaT = new javax.swing.JLabel();
        paneProccess = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAProccess = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Thermodynamics - Linear Expansion");

        paneResult.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Result", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14))); // NOI18N

        btnCalculate.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        btnCalculate.setText("Calculate");
        btnCalculate.setToolTipText("Calculate the Result");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        lblTitleSelected.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        lblTitleSelected.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleSelected.setText("Selected");

        lblResult.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        lblResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResult.setText("00");

        javax.swing.GroupLayout paneResultLayout = new javax.swing.GroupLayout(paneResult);
        paneResult.setLayout(paneResultLayout);
        paneResultLayout.setHorizontalGroup(
            paneResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneResultLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCalculate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTitleSelected, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        paneResultLayout.setVerticalGroup(
            paneResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneResultLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCalculate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitleSelected)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblResult)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        paneValues.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Linear Expansion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 18))); // NOI18N

        lblLinearExpansionIcon.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        lblLinearExpansionIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLinearExpansionIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/phyisics/resources/linear_expansion.jpg"))); // NOI18N

        lblTitleInitialL.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        lblTitleInitialL.setForeground(new java.awt.Color(0, 84, 140));
        lblTitleInitialL.setText("<html>L<sub>I</sub></html>");

        lblTitleFinalL.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        lblTitleFinalL.setForeground(new java.awt.Color(0, 84, 140));
        lblTitleFinalL.setText("<html>L<sub>F</sub></html>");

        lblTitleInitialT.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        lblTitleInitialT.setForeground(new java.awt.Color(180, 24, 2));
        lblTitleInitialT.setText("<html>&theta;<sub>I</sub></html>");

        lblTitleAlpha.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        lblTitleAlpha.setForeground(new java.awt.Color(26, 144, 0));
        lblTitleAlpha.setText("<html>&alpha;</html>");

        txtInitialL.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        txtInitialL.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtInitialL.setToolTipText("Enter with the Initial Length");

        txtInitialT.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        txtInitialT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtInitialT.setToolTipText("Enter with the Initial Temperature");

        txtAlpha.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        txtAlpha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAlpha.setToolTipText("Enter with the Coefficient");

        lblTitleFinalT.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        lblTitleFinalT.setForeground(new java.awt.Color(180, 24, 2));
        lblTitleFinalT.setText("<html>&theta;<sub>F</sub></html>");

        txtFinalT.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        txtFinalT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFinalT.setToolTipText("Enter with the Final Temperature");

        txtFinalL.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        txtFinalL.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFinalL.setToolTipText("Enter with the Final Length");

        javax.swing.GroupLayout paneValuesLayout = new javax.swing.GroupLayout(paneValues);
        paneValues.setLayout(paneValuesLayout);
        paneValuesLayout.setHorizontalGroup(
            paneValuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneValuesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneValuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtInitialL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitleInitialL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitleFinalL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFinalL, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblLinearExpansionIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneValuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneValuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtFinalT, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addComponent(lblTitleFinalT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblTitleInitialT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtInitialT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneValuesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitleAlpha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtAlpha, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175))
        );
        paneValuesLayout.setVerticalGroup(
            paneValuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneValuesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneValuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblLinearExpansionIcon)
                    .addGroup(paneValuesLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(lblTitleInitialL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtInitialL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(lblTitleFinalL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFinalL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneValuesLayout.createSequentialGroup()
                        .addComponent(lblTitleInitialT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtInitialT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTitleFinalT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFinalT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(paneValuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAlpha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitleAlpha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        paneSelect.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Select One", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14))); // NOI18N

        btnAlpha.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        btnAlpha.setText("Linear Coefficient");
        btnAlpha.setToolTipText("Select the Linear Coefficient");
        btnAlpha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlphaActionPerformed(evt);
            }
        });

        btnInitialT.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        btnInitialT.setText("Initial Temperature");
        btnInitialT.setToolTipText("Select the Initial Temperature");
        btnInitialT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInitialTActionPerformed(evt);
            }
        });

        btnFinalT.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        btnFinalT.setText("FinalTemperature");
        btnFinalT.setToolTipText("Select the Final Temperature");
        btnFinalT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalTActionPerformed(evt);
            }
        });

        btnFinalL.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        btnFinalL.setText("Final Length");
        btnFinalL.setToolTipText("Select the Final Length");
        btnFinalL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneSelectLayout = new javax.swing.GroupLayout(paneSelect);
        paneSelect.setLayout(paneSelectLayout);
        paneSelectLayout.setHorizontalGroup(
            paneSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneSelectLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInitialT, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                    .addComponent(btnAlpha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFinalT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFinalL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        paneSelectLayout.setVerticalGroup(
            paneSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneSelectLayout.createSequentialGroup()
                .addComponent(btnAlpha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFinalL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInitialT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFinalT)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        paneMoreInformation.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "More Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14))); // NOI18N

        lblTitleDeltaL.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        lblTitleDeltaL.setForeground(new java.awt.Color(0, 84, 140));
        lblTitleDeltaL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleDeltaL.setText("<html>&Delta;L: </html>");

        lblTitleDeltaT.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        lblTitleDeltaT.setForeground(new java.awt.Color(180, 24, 2));
        lblTitleDeltaT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleDeltaT.setText("<html>&Delta;&theta;: </html>");

        lblDeltaL.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        lblDeltaL.setForeground(new java.awt.Color(0, 84, 140));
        lblDeltaL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDeltaL.setText("0");

        lblDeltaT.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        lblDeltaT.setForeground(new java.awt.Color(180, 24, 2));
        lblDeltaT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDeltaT.setText("0");

        javax.swing.GroupLayout paneMoreInformationLayout = new javax.swing.GroupLayout(paneMoreInformation);
        paneMoreInformation.setLayout(paneMoreInformationLayout);
        paneMoreInformationLayout.setHorizontalGroup(
            paneMoreInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneMoreInformationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneMoreInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTitleDeltaL)
                    .addComponent(lblTitleDeltaT, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneMoreInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDeltaT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDeltaL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        paneMoreInformationLayout.setVerticalGroup(
            paneMoreInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneMoreInformationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneMoreInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitleDeltaL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDeltaL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneMoreInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitleDeltaT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDeltaT))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        paneProccess.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Proccess", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14))); // NOI18N

        txtAProccess.setColumns(20);
        txtAProccess.setRows(5);
        jScrollPane2.setViewportView(txtAProccess);

        javax.swing.GroupLayout paneProccessLayout = new javax.swing.GroupLayout(paneProccess);
        paneProccess.setLayout(paneProccessLayout);
        paneProccessLayout.setHorizontalGroup(
            paneProccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        paneProccessLayout.setVerticalGroup(
            paneProccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(paneValues, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paneProccess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paneResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paneSelect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paneMoreInformation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(paneValues, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(paneProccess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(paneSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(paneResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(paneMoreInformation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlphaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlphaActionPerformed
        // TODO add your handling code here:
        selectEnabledComponents(true, true, true, true, false);
        lblTitleSelected.setText("Linear Coefficient");
        // set selected as Alpha
        selected = 'a';
    }//GEN-LAST:event_btnAlphaActionPerformed

    private void btnInitialTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInitialTActionPerformed
        // TODO add your handling code here:
        selectEnabledComponents(true, false, true, true, true);
        lblTitleSelected.setText("Initial Temperature");
        // set selected as Initial Temperature
        selected = 't';
    }//GEN-LAST:event_btnInitialTActionPerformed

    private void btnFinalTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalTActionPerformed
        // TODO add your handling code here:
        selectEnabledComponents(true, true, true, false, true);
        lblTitleSelected.setText("Final Temperature");
        // set selected as Final Temperature
        selected = 'T';
    }//GEN-LAST:event_btnFinalTActionPerformed

    private void btnFinalLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalLActionPerformed
        // TODO add your handling code here:
        selectEnabledComponents(true, true, false, true, true);
        lblTitleSelected.setText("Final Length");
        // set selected as Final Length
        selected = 'L';
    }//GEN-LAST:event_btnFinalLActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        // TODO add your handling code here:
        double initialL, initialT, finalL, finalT, alpha;

        try {
            initialL = Double.parseDouble(txtInitialL.getText());
            finalL = Double.parseDouble(txtFinalL.getText());
            initialT = Double.parseDouble(txtInitialT.getText());
            finalT = Double.parseDouble(txtFinalT.getText());
            alpha = Double.parseDouble(txtAlpha.getText());
            // Handle the operation by the selected one
            lc.handleOperations(selected, lblResult, lblDeltaL, lblDeltaT, txtAProccess, initialL, finalL, initialT, finalT, alpha);
            txtAProccess.setText(txtAProccess.getText() + "Created by Derick Felix!");
        } catch (NumberFormatException e) {
            lblResult.setForeground(Color.red.darker());
            lblResult.setText("Try to put numbers, ex: 3.43e-2");
            System.out.println("Error: " + e);
        }
    }//GEN-LAST:event_btnCalculateActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlpha;
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnFinalL;
    private javax.swing.JButton btnFinalT;
    private javax.swing.JButton btnInitialT;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDeltaL;
    private javax.swing.JLabel lblDeltaT;
    private javax.swing.JLabel lblLinearExpansionIcon;
    private javax.swing.JLabel lblResult;
    private javax.swing.JLabel lblTitleAlpha;
    private javax.swing.JLabel lblTitleDeltaL;
    private javax.swing.JLabel lblTitleDeltaT;
    private javax.swing.JLabel lblTitleFinalL;
    private javax.swing.JLabel lblTitleFinalT;
    private javax.swing.JLabel lblTitleInitialL;
    private javax.swing.JLabel lblTitleInitialT;
    private javax.swing.JLabel lblTitleSelected;
    private javax.swing.JPanel paneMoreInformation;
    private javax.swing.JPanel paneProccess;
    private javax.swing.JPanel paneResult;
    private javax.swing.JPanel paneSelect;
    private javax.swing.JPanel paneValues;
    private javax.swing.JTextArea txtAProccess;
    private javax.swing.JTextField txtAlpha;
    private javax.swing.JTextField txtFinalL;
    private javax.swing.JTextField txtFinalT;
    private javax.swing.JTextField txtInitialL;
    private javax.swing.JTextField txtInitialT;
    // End of variables declaration//GEN-END:variables
}
